### ISSUE TITLE
SSL error on retrieving Norad data

### ISSUE THREAD

**Issue by markbrough** [IATI/IATI-Datastore#242] opened 2016-03-28 09:33 UTC
http://datastore.iatistandard.org/api/1/error/dataset/norad-activity_file

While trying to retrieve file from:
https://www.norad.no/contentassets/23a62a96ff8b43f1886fc0619b51214f/iati_report_20151215.xml

IATI Registry URL:
http://iatiregistry.org/dataset/norad-activity_file

**Comment by andylolz** [comment] 2017-03-29 16:30
So https://www.norad.no provides two certificates: a valid [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) one, and an invalid non-SNI one. You can see that in the test results here:
https://www.ssllabs.com/ssltest/analyze.html?d=www.norad.no

requests is using the invalid non-SNI certificate, and erroring (because it’s invalid). To make requests use the SNI certificate, it looks like you need to either:
 * [upgrade requests](https://github.com/IATI/IATI-Datastore/blob/66cdf804/requirements.txt#L26) to >=2.13.0, and upgrade python to >=2.7.9, or
 * install [a bunch of other stuff](https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484)

**Comment by andylolz** [comment] 2017-03-30 09:49
NB I was able to recreate the error on ubuntu 14.04 using python 2.7.6, and was able to resolve it via all three methods.

**Comment by dalepotter** [comment] 2017-04-06 14:12
Thanks for the further investigation @andylolz 

I can confirm that the Datastore is running is running an old version of python, which I have now upgraded.  We'll need to wait until the datastore does it's periodic update (probably this evening) before we can see if this has fully fixed the problem with Norad's files.

We'll know the issue is resolved when [this API call](
http://datastore.iatistandard.org/api/1/access/activity.xml?registry-dataset=norad-activity_file) returns a similar `total-count` number to that shown on the Registry dataset: http://iatiregistry.org/dataset/norad-activity_file

**Comment by dalepotter** [comment] 2017-04-07 15:29
Having just checked this again, both the [Datastore API]](http://datastore.iatistandard.org/api/1/access/activity.xml?registry-dataset=norad-activity_file) and the activity count in the IATI Registry metadata section for [this dataset](http://iatiregistry.org/dataset/norad-activity_file) are currently both returning 3926.

Given this, I will now close this issue!

**Closed by dalepotter** 2017-04-07 15:29 UTC
